spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-client
eureak: 
  instance: 
    hostname: eureka7001.com #冒号后面必须要有空格
  client: 
    register-with-eureka: false #当前的eureka-server 自己不能注册进服务列表中
    fetch-registry: false #不能通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
---
server: 
  port: 7001 #注册中心占用7001端口，冒号后面必须有空格
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-eureka-client
eureka: 
  instance: 
    hostname: eureak7001.com
  client: 
    register-with-eureka: false 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/